# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from main_module import recommendation


class Ui_MainWindow(object):
    def __init__(self):
        self.data_list = []
        self.header = ['Hotel Name', 'Star Rating',  'Price', 'Address', 'Description']

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1292, 767)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(45, 58, 127);\n"
"color: rgb(400, 233, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(350, -10, 641, 171))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(35)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.userName_label = QtWidgets.QLabel(self.centralwidget)
        self.userName_label.setGeometry(QtCore.QRect(54, 228, 111, 31))
        self.userName_label.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.userName_label.setFont(font)
        self.userName_label.setStyleSheet("font: 87 10pt \"Segoe UI Black\";")
        self.userName_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.userName_label.setObjectName("userName_label")
        self.userName_input = QtWidgets.QLineEdit(self.centralwidget)
        self.userName_input.setGeometry(QtCore.QRect(170, 230, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userName_input.setFont(font)
        self.userName_input.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(130, 98, 157);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(200, 133, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(200, 133, 255);\n"
"    color:rgb(255, 255, 255)\n"
"    background-color: rgb(134, 100, 161);\n"
"}")
        self.userName_input.setObjectName("userName_input")
        self.budget_labl = QtWidgets.QLabel(self.centralwidget)
        self.budget_labl.setGeometry(QtCore.QRect(85, 278, 81, 31))
        self.budget_labl.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.budget_labl.setFont(font)
        self.budget_labl.setStyleSheet("font: 87 10pt \"Segoe UI Black\";")
        self.budget_labl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.budget_labl.setObjectName("budget_labl")
        self.budget_input = QtWidgets.QLineEdit(self.centralwidget)
        self.budget_input.setGeometry(QtCore.QRect(171, 280, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.budget_input.setFont(font)
        self.budget_input.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(130, 98, 157);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(200, 133, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(200, 133, 255);\n"
"    color:rgb(255, 255, 255)\n"
"    background-color: rgb(134, 100, 161);\n"
"}")
        self.budget_input.setObjectName("budget_input")
        self.city_dropDown = QtWidgets.QComboBox(self.centralwidget)
        self.city_dropDown.setGeometry(QtCore.QRect(172, 379, 211, 31))
        self.city_dropDown.setStyleSheet("QComboBox:focus {\n"
"    border: 2px solid rgb(200, 133, 255);\n"
"    color:rgb(200, 133, 255);\n"
"    background-color: rgb(134, 100, 161);\n"
"}\n"
"QComboBox {\n"
"    \n"
"    font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"QComboBox:hover {\n"
"    background-color:rgb(135, 101, 162);\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"    selection-background-color:  rgb(134, 100, 161);\n"
"}\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}")
        self.city_dropDown.setObjectName("city_dropDown")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_dropDown.addItem("")
        self.city_lebel = QtWidgets.QLabel(self.centralwidget)
        self.city_lebel.setGeometry(QtCore.QRect(60, 378, 101, 31))
        self.city_lebel.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.city_lebel.setFont(font)
        self.city_lebel.setStyleSheet("font: 87 10pt \"Segoe UI Black\";")
        self.city_lebel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.city_lebel.setObjectName("city_lebel")
        self.breakfast_dropDown = QtWidgets.QComboBox(self.centralwidget)
        self.breakfast_dropDown.setGeometry(QtCore.QRect(171, 429, 211, 31))
        self.breakfast_dropDown.setStyleSheet("QComboBox:focus {\n"
"    border: 2px solid rgb(200, 133, 255);\n"
"    color:rgb(200, 133, 255);\n"
"    background-color: rgb(134, 100, 161);\n"
"}\n"
"QComboBox {\n"
"    \n"
"    font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"QComboBox:hover {\n"
"    background-color:rgb(135, 101, 162);\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"    selection-background-color:  rgb(134, 100, 161);\n"
"}\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}")
        self.breakfast_dropDown.setObjectName("breakfast_dropDown")
        self.breakfast_dropDown.addItem("")
        self.breakfast_dropDown.addItem("")
        self.breakfast_label = QtWidgets.QLabel(self.centralwidget)
        self.breakfast_label.setGeometry(QtCore.QRect(24, 428, 141, 31))
        self.breakfast_label.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.breakfast_label.setFont(font)
        self.breakfast_label.setStyleSheet("font: 87 10pt \"Segoe UI Black\";")
        self.breakfast_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.breakfast_label.setObjectName("breakfast_label")
        self.wifi_dropDown = QtWidgets.QComboBox(self.centralwidget)
        self.wifi_dropDown.setGeometry(QtCore.QRect(172, 481, 211, 31))
        self.wifi_dropDown.setStyleSheet("QComboBox:focus {\n"
"    border: 2px solid rgb(200, 133, 255);\n"
"    color:rgb(200, 133, 255);\n"
"    background-color: rgb(134, 100, 161);\n"
"}\n"
"QComboBox {\n"
"    \n"
"    font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"QComboBox:hover {\n"
"    background-color:rgb(135, 101, 162);\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"    selection-background-color:  rgb(134, 100, 161);\n"
"}\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}")
        self.wifi_dropDown.setObjectName("wifi_dropDown")
        self.wifi_dropDown.addItem("")
        self.wifi_dropDown.addItem("")
        self.wifi_label = QtWidgets.QLabel(self.centralwidget)
        self.wifi_label.setGeometry(QtCore.QRect(69, 480, 91, 31))
        self.wifi_label.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.wifi_label.setFont(font)
        self.wifi_label.setStyleSheet("font: 87 10pt \"Segoe UI Black\";")
        self.wifi_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wifi_label.setObjectName("wifi_label")
        self.swimming_label = QtWidgets.QLabel(self.centralwidget)
        self.swimming_label.setGeometry(QtCore.QRect(14, 535, 151, 31))
        self.swimming_label.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.swimming_label.setFont(font)
        self.swimming_label.setStyleSheet("font: 87 10pt \"Segoe UI Black\";")
        self.swimming_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.swimming_label.setObjectName("swimming_label")
        self.swimming_dropDown = QtWidgets.QComboBox(self.centralwidget)
        self.swimming_dropDown.setGeometry(QtCore.QRect(172, 536, 211, 31))
        self.swimming_dropDown.setStyleSheet("QComboBox:focus {\n"
"    border: 2px solid rgb(200, 133, 255);\n"
"    color:rgb(200, 133, 255);\n"
"    background-color: rgb(134, 100, 161);\n"
"}\n"
"QComboBox {\n"
"    \n"
"    font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"QComboBox:hover {\n"
"    background-color:rgb(135, 101, 162);\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"    selection-background-color:  rgb(134, 100, 161);\n"
"}\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}")
        self.swimming_dropDown.setObjectName("swimming_dropDown")
        self.swimming_dropDown.addItem("")
        self.swimming_dropDown.addItem("")
        self.recommend_btn = QtWidgets.QPushButton(self.centralwidget)
        self.recommend_btn.setGeometry(QtCore.QRect(31, 598, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.recommend_btn.setFont(font)
        self.recommend_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.recommend_btn.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"    border-color:rgb(130, 98, 157);\n"
"    border-radius: 20px;\n"
"    color: rgb(200, 133, 255);\n"
"    background-color:rgb(106, 79, 127);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(135, 101, 162);\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"}")
        self.recommend_btn.setAutoDefault(False)
        self.recommend_btn.setObjectName("recommend_btn")
        self.recommend_btn.clicked.connect(self.process_inputs)
        self.credit_label = QtWidgets.QLabel(self.centralwidget)
        self.credit_label.setGeometry(QtCore.QRect(-34, 730, 1321, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.credit_label.sizePolicy().hasHeightForWidth())
        self.credit_label.setSizePolicy(sizePolicy)
        self.credit_label.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.credit_label.setFont(font)
        self.credit_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.credit_label.setObjectName("credit_label")
        self.table_view = QtWidgets.QTableView(self.centralwidget)
        self.table_view.setGeometry(QtCore.QRect(450, 230, 831, 481))
        self.table_view.setStyleSheet("QTableView {\n"
"    color: rgb(200, 133, 255);\n"
"    \n"
"    font: 87 10pt \"Segoe UI Black\";\n"
"}")
        self.table_view.setObjectName("table_view")
        self.table_view.horizontalHeader().setStyleSheet("QHeaderView { font: 87 10pt \"Segoe UI Black\"; }");
        self.text_label = QtWidgets.QLabel(self.centralwidget)
        self.text_label.setGeometry(QtCore.QRect(450, 190, 321, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_label.sizePolicy().hasHeightForWidth())
        self.text_label.setSizePolicy(sizePolicy)
        self.text_label.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.text_label.setFont(font)
        self.text_label.setStyleSheet("font: 87 10pt \"Segoe UI Black\";")
        self.text_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text_label.setObjectName("text_label")
        self.room_lable = QtWidgets.QLabel(self.centralwidget)
        self.room_lable.setGeometry(QtCore.QRect(84, 328, 81, 31))
        self.room_lable.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.room_lable.setFont(font)
        self.room_lable.setStyleSheet("font: 87 10pt \"Segoe UI Black\";")
        self.room_lable.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.room_lable.setObjectName("room_lable")
        self.rooms_input = QtWidgets.QLineEdit(self.centralwidget)
        self.rooms_input.setGeometry(QtCore.QRect(170, 330, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rooms_input.setFont(font)
        self.rooms_input.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(130, 98, 157);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(200, 133, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(144, 96, 185);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(200, 133, 255);\n"
"    color:rgb(255, 255, 255)\n"
"    background-color: rgb(134, 100, 161);\n"
"}")
        self.rooms_input.setObjectName("rooms_input")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def process_inputs(self):
        global result
        name = self.userName_input.text()
        price = int(self.budget_input.text())
        city = self.city_dropDown.currentText()
        rooms = int(self.rooms_input.text())
        breakfast = 1 if self.breakfast_dropDown.currentText() == 'YES' else 0
        wifi = 1 if self.wifi_dropDown.currentText() == 'YES' else 0
        swimming = 1 if self.swimming_dropDown.currentText() == 'YES' else 0
        try:
            hotels_name, hotels_rating, hotels_price, hotels_add, hotels_des  = recommendation(city, breakfast, wifi, swimming, price, rooms)
            if len(hotels_price) == 0:
                raise TypeError
            self.data_list = list(zip(hotels_name, hotels_rating, hotels_price, hotels_add, hotels_des))
            table_model = MyTableModel(self, self.data_list, self.header)
            self.table_view.setModel(table_model)
            self.table_view.resizeColumnsToContents()
        except:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setText("No Result Found!")
            msg.setStandardButtons(QtWidgets.QMessageBox.Ok | QtWidgets.QMessageBox.Cancel)
            msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Hotel </span>Recommendation<br/>System</p></body></html>"))
        self.userName_label.setText(_translate("MainWindow", "<html><head/><body><p>User Name :</p></body></html>"))
        self.userName_input.setPlaceholderText(_translate("MainWindow", "Enter Name"))
        self.budget_labl.setText(_translate("MainWindow", "<html><head/><body><p>Budget :</p></body></html>"))
        self.budget_input.setPlaceholderText(_translate("MainWindow", "Enter Budget"))
        self.city_dropDown.setItemText(0, _translate("MainWindow", "Mumbai"))
        self.city_dropDown.setItemText(1, _translate("MainWindow", "Delhi"))
        self.city_dropDown.setItemText(2, _translate("MainWindow", "Bangalore"))
        self.city_dropDown.setItemText(3, _translate("MainWindow", "Chennai"))
        self.city_dropDown.setItemText(4, _translate("MainWindow", "Hyderabad"))
        self.city_dropDown.setItemText(5, _translate("MainWindow", "Ahmedabad"))
        self.city_dropDown.setItemText(6, _translate("MainWindow", "Kolkata"))
        self.city_dropDown.setItemText(7, _translate("MainWindow", "Surat"))
        self.city_dropDown.setItemText(8, _translate("MainWindow", "Pune"))
        self.city_dropDown.setItemText(9, _translate("MainWindow", "Jaipur"))
        self.city_dropDown.setItemText(10, _translate("MainWindow", "Thrissur"))
        self.city_dropDown.setItemText(11, _translate("MainWindow", "Lucknow"))
        self.city_dropDown.setItemText(12, _translate("MainWindow", "Kanpur"))
        self.city_dropDown.setItemText(13, _translate("MainWindow", "Amritsar"))
        self.city_dropDown.setItemText(14, _translate("MainWindow", "Indore"))
        self.city_dropDown.setItemText(15, _translate("MainWindow", "Agra"))
        self.city_dropDown.setItemText(16, _translate("MainWindow", "Madurai"))
        self.city_dropDown.setItemText(17, _translate("MainWindow", "Goa"))
        self.city_dropDown.setItemText(18, _translate("MainWindow", "Rajkot"))
        self.city_dropDown.setItemText(19, _translate("MainWindow", "Varanasi"))
        self.city_dropDown.setItemText(20, _translate("MainWindow", "Srinagar"))
        self.city_dropDown.setItemText(21, _translate("MainWindow", "Jodhpur"))
        self.city_dropDown.setItemText(22, _translate("MainWindow", "Chandigarh"))
        self.city_dropDown.setItemText(23, _translate("MainWindow", "Thiruvanthipuram"))
        self.city_dropDown.setItemText(24, _translate("MainWindow", "Guwahati"))
        self.city_dropDown.setItemText(25, _translate("MainWindow", "Mysore"))
        self.city_dropDown.setItemText(26, _translate("MainWindow", "Bhubaneswar"))
        self.city_dropDown.setItemText(27, _translate("MainWindow", "Kochi"))
        self.city_dropDown.setItemText(28, _translate("MainWindow", "Mangalore"))
        self.city_dropDown.setItemText(29, _translate("MainWindow", "Udaipur"))
        self.city_dropDown.setItemText(30, _translate("MainWindow", "Haridwar"))
        self.city_dropDown.setItemText(31, _translate("MainWindow", "Puri"))
        self.city_dropDown.setItemText(32, _translate("MainWindow", "Shimla"))
        self.city_dropDown.setItemText(33, _translate("MainWindow", "Panchkula"))
        self.city_dropDown.setItemText(34, _translate("MainWindow", "Darjeeling"))
        self.city_dropDown.setItemText(35, _translate("MainWindow", "Rishikesh"))
        self.city_dropDown.setItemText(36, _translate("MainWindow", "Gangtok"))
        self.city_dropDown.setItemText(37, _translate("MainWindow", "Ooty"))
        self.city_dropDown.setItemText(38, _translate("MainWindow", "Jaisalmer"))
        self.city_dropDown.setItemText(39, _translate("MainWindow", "Nainital"))
        self.city_dropDown.setItemText(40, _translate("MainWindow", "Munnar"))
        self.city_dropDown.setItemText(41, _translate("MainWindow", "Manali"))
        self.city_lebel.setText(_translate("MainWindow", "<html><head/><body><p>Select City :</p></body></html>"))
        self.breakfast_dropDown.setItemText(0, _translate("MainWindow", "YES"))
        self.breakfast_dropDown.setItemText(1, _translate("MainWindow", "NO"))
        self.breakfast_label.setText(_translate("MainWindow", "<html><head/><body><p>Free Breakfast :</p></body></html>"))
        self.wifi_dropDown.setItemText(0, _translate("MainWindow", "YES"))
        self.wifi_dropDown.setItemText(1, _translate("MainWindow", "NO"))
        self.wifi_label.setText(_translate("MainWindow", "<html><head/><body><p>Free Wifi :</p></body></html>"))
        self.swimming_label.setText(_translate("MainWindow", "<html><head/><body><p>Swimming Pool :</p></body></html>"))
        self.swimming_dropDown.setItemText(0, _translate("MainWindow", "YES"))
        self.swimming_dropDown.setItemText(1, _translate("MainWindow", "NO"))
        self.recommend_btn.setText(_translate("MainWindow", "Recommend Hotels"))
        self.credit_label.setText(_translate("MainWindow", "<strong>Created By</strong> Kartiki, Shreyash, Shweta, Ashutosh"))
        self.text_label.setText(_translate("MainWindow", "<html><head/><body><p>We recommend you following hotels</p></body></html>"))
        self.room_lable.setText(_translate("MainWindow", "<html><head/><body><p>Rooms :</p></body></html>"))
        self.rooms_input.setPlaceholderText(_translate("MainWindow", "Enter no. of rooms"))

class MyTableModel(QtCore.QAbstractTableModel):
    def __init__(self, parent, mylist, header, *args):
        QtCore.QAbstractTableModel.__init__(self)
        self.mylist = mylist
        self.header = header
    def rowCount(self, parent):
        return len(self.mylist)
    def columnCount(self, parent):
        return len(self.mylist[0])
    def data(self, index, role):
        if not index.isValid():
            return None
        elif role != QtCore.Qt.DisplayRole:
            return None
        return self.mylist[index.row()][index.column()]
    def headerData(self, col, orientation, role):
        if orientation == QtCore.Qt.Horizontal and role == QtCore.Qt.DisplayRole:
            return self.header[col]
        return None
    def sort(self, col, order):
        """sort table by given column number col"""
        self.emit(SIGNAL("layoutAboutToBeChanged()"))
        self.mylist = sorted(self.mylist,
            key=operator.itemgetter(col))
        if order == QtCore.Qt.DescendingOrder:
            self.mylist.reverse()
        self.emit(SIGNAL("layoutChanged()"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
